defaults: &defaults
  spotify_api:
    client_id: <%= ENV['SPOTIFY_CLIENT_ID'] %>
    client_secret: <%= ENV['SPOTIFY_CLIENT_SECRET'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
